export default {
  ItemContents: {
    general: "Tổng quan",
    asset: "Tài sản",
    path: "Tài sản HT-ĐB",
    tool: "Công cụ dụng cụ",
    category: "Danh mục",
    search: "Tra cứu",
    report: "Báo cáo",
  },
  Title: {
    home: "Trang chủ",
    extension: "Mở rộng sidebar",
    collapse: "Thu gọn sidebar",
    more: "Xem thêm",
    year: "Năm",
    increase: "Tăng",
    decrease: "Giảm",
    "financial-department": "Sở tài chính",
    "search-input": "Tìm kiếm theo tên, mã tài sản",
    "asset-category-filter": "Lọc theo loại tài sản",
    "department-filter": "lọc theo bộ phận sử dụng",
    add: "Thêm mới tài sản",
    export: "Xuất dữ liệu",
    delete: "Xóa bản ghi",
    edit: "Sửa",
    duplicate: "Nhân bản",
    limit: "Số lượng bản ghi hiển thị",
    pre: "Trang trước",
    next: "Trang sau",
    close: "Đóng",
    save: "Lưu thông tin",
    cancel: "Hủy",
  },
  Logo: {
    qlts: "MISA QLTS",
  },
  PageTitle: {
    assetList: "Danh sách tài sản",
  },
  HeaderTitle: {
    account: "Tài khoản",
    help: "Hỗ trợ",
    menu: "Danh mục",
    notification: "Thông báo",
  },
  Placeholder: {
    "asset-search": "Tìm kiếm tài sản",
    category: "Loại tài sản",
    department: "Bộ phận sử dụng",
  },
  ButtonName: {
    "asset-add": "Thêm tài sản",
  },
  URLs: {
    department: "https://localhost:44385/api/v1/Departments",
    "asset-type": "https://localhost:44385/api/v1/AssetCategories",
    getAllAsset: "https://localhost:44385/api/v1/Assets",
  },
  Abbreviations: {
    path: "Tài sản Hệ thống - Đường bộ",
    depreciation: "Hao mòn/Khấu hao lũy kế",
    STT: "Số thứ tự",
  },
  Columns: {
    stt: "STT",
    "asset-code": "Mã tài sản",
    "asset-name": "Tên tài sản",
    "asset-category": "Loại tài sản",
    department: "Bộ phận sử dụng",
    quantity: "Số lượng",
    cost: "Nguyên giá",
    depreciation: "HM/KH lũy kế",
    "residual-value": "Giá trị còn lại",
    feature: "Tính năng",
  },
  PopupTitle: {
    add: "Thêm mới tài sản",
    edit: "Sửa tài sản",
  },
};
