export default {
  ItemContents: {
    general: "Tổng quan",
    asset: "Tài sản",
    path: "Tài sản HT-ĐB",
    tool: "Công cụ dụng cụ",
    category: "Danh mục",
    search: "Tra cứu",
    report: "Báo cáo",
  },
  Title: {
    home: "Trang chủ",
    extension: "Mở rộng sidebar",
    collapse: "Thu gọn sidebar",
    more: "Xem thêm",
    year: "Năm",
    increase: "Tăng",
    decrease: "Giảm",
    "financial-department": "Sở tài chính",
    "search-input": "Tìm kiếm theo tên, mã tài sản",
    "asset-category-filter": "Lọc theo loại tài sản",
    "department-filter": "lọc theo bộ phận sử dụng",
    add: "Thêm mới tài sản",
    export: "Xuất dữ liệu",
    edit: "Sửa",
    duplicate: "Nhân bản",
    limit: "Số lượng bản ghi hiển thị",
    pre: "Trang trước",
    next: "Trang sau",
    close: "Đóng",
    save: "Lưu thông tin",
    update: "Cập nhật thông tin",
    noSave: "Không lưu thông tin thay đổi",
    cancel: "Hủy bỏ",
    delete: "Xóa tài sản",
  },
  Logo: {
    qlts: "MISA QLTS",
  },
  PageTitle: {
    assetList: "Danh sách tài sản",
  },
  HeaderTitle: {
    account: "Tài khoản",
    help: "Hỗ trợ",
    menu: "Danh mục",
    notification: "Thông báo",
  },
  Placeholder: {
    "asset-search": "Tìm kiếm tài sản",
    category: "Loại tài sản",
    department: "Bộ phận sử dụng",
    department_code: "Chọn mã bộ phận sử dụng",
    asset_category_code: "Chọn mã loại tài sản",
  },
  ButtonName: {
    "asset-add": "Thêm tài sản",
  },
  URLs: {
    department: "http://localhost:11799/api/v1/Departments",
    "asset-type": "http://localhost:11799/api/v1/FixedAssetCategories",
    getAllAsset: "http://localhost:11799/api/v1/FixedAssets",
  },
  Abbreviations: {
    path: "Tài sản Hệ thống - Đường bộ",
    depreciation: "Hao mòn/Khấu hao lũy kế",
    STT: "Số thứ tự",
  },
  Columns: {
    stt: "STT",
    "asset-code": "Mã tài sản",
    "asset-name": "Tên tài sản",
    "asset-category": "Loại tài sản",
    department: "Bộ phận sử dụng",
    quantity: "Số lượng",
    cost: "Nguyên giá",
    depreciation: "HM/KH lũy kế",
    residual_value: "Giá trị còn lại",
    feature: "Tính năng",
  },
  PopupTitle: {
    add: "Thêm mới tài sản",
    edit: "Sửa tài sản",
    duplicate: "Nhân bản tài sản",
  },
  PopupLabel: {
    fixed_asset_code: "Mã tài sản",
    fixed_asset_name: "Tên tài sản",
    department_code: "Mã bộ phận sử dụng",
    department_name: "Tên bộ phận sử dụng",
    fixed_asset_category_code: "Mã loại tài sản",
    fixed_asset_category_name: "Tên loại tài sản",
    quantity: "Số lượng",
    cost: "Nguyên giá",
    life_time: "Số năm sử dụng",
    depreciation_rate: "Tỉ lệ hao mòn (%)",
    depreciation_value: "Giá trị hao mòn năm",
    tracked_year: "Năm theo dõi",
    purchase_date: "Ngày mua",
    production_date: "Ngày bắt đầu sử dụng",
  },
  InputLength: {
    fixed_asset_code: 100,
    fixed_asset_name: 255,
    department_code: 50,
    fixed_asset_category_code: 50,
  },
  ComboboxInfo: {
    firstCol: "Mã",
  },
  ButtonContent: {
    save: "Lưu",
    cancel: "Hủy",
    remove: "Hủy bỏ",
    delete: "Xóa",
    no: "Không",
    noSave: "Không lưu",
    close: "Đóng",
  },
  Name: {
    export: "export",
    delete: "delete",
  },
  ErrorMessage: {
    blank: "là thông tin bắt buộc",
  },
  WarningMessage: {
    info: "Cần phải nhập thông tin",
    depreciation: "Tỉ lệ hao mòn phải bằng 1/Số năm sử dụng",
    costAndDepreciationValue: "Hao mòn năm phải nhỏ hơn hoặc bằng nguyên giá",
  },
  RequiredData: {
    fixed_asset_id: false,
    fixed_asset_code: true,
    fixed_asset_name: true,
    department_code: true,
    department_name: false,
    fixed_asset_category_code: true,
    fixed_asset_category_name: false,
    quantity: false,
    cost: true,
    life_time: true,
    depreciation_rate: false,
    depreciation_value: true,
    tracked_year: false,
    purchase_date: false,
    production_date: false,
  },
  PopupField: {
    fixed_asset_id: "fixed_asset_id",
    fixed_asset_code: "fixed_asset_code",
    fixed_asset_name: "fixed_asset_name",
    department_code: "department_code",
    department_name: "department_name",
    fixed_asset_category_code: "fixed_asset_category_code",
    fixed_asset_category_name: "fixed_asset_category_name",
    quantity: "quantity",
    cost: "cost",
    life_time: "life_time",
    depreciation_rate: "depreciation_rate",
    depreciation_value: "depreciation_value",
    tracked_year: "tracked_year",
    purchase_date: "purchase_date",
    production_date: "production_date",
  },
  ToastInfo: {
    addSuccess: "Lưu dữ liệu thành công",
    updateSuccess: "Cập nhật dữ liệu thành công",
    deleteSuccess: "Xóa bản ghi thành công",
    duplicateSuccess: "Nhân bản dữ liệu thành công",
    deleteMultiSuccess: "bản ghi đã được xóa thành công",
    error: "Có lỗi xảy ra!",
  },
};
